import{dataApi}from'../../../lib/neon/data';import type{CaffeineIntake,CaffeineIntakeInput,CaffeinePreset,CaffeinePresetInput}from'../types'
const CHANGED='studyos:caffeine-changed';const notify=()=>window.dispatchEvent(new Event(CHANGED));export function onCaffeineChanged(fn:()=>void){window.addEventListener(CHANGED,fn);return()=>window.removeEventListener(CHANGED,fn)}function fail(error:unknown){return new Error(error&&typeof error==='object'&&'message'in error?String(error.message):'Caffeine request failed')}
function map(row:Record<string,unknown>):CaffeineIntake{return{id:String(row.id),source:String(row.source),caffeineMg:Number(row.caffeine_mg),startedAt:String(row.started_at),durationMinutes:Number(row.duration_minutes),note:row.note?String(row.note):null}}
export async function listCaffeineIntakes(from:Date,to:Date){const{data,error}=await dataApi.from('caffeine_intakes').select('id,source,caffeine_mg,started_at,duration_minutes,note').gte('started_at',from.toISOString()).lte('started_at',to.toISOString()).order('started_at',{ascending:false});if(error)throw fail(error);return(data??[]).map(row=>map(row as Record<string,unknown>))}
export async function createCaffeineIntake(input:CaffeineIntakeInput){const{error}=await dataApi.from('caffeine_intakes').insert({source:input.source.trim(),caffeine_mg:input.caffeineMg,started_at:input.startedAt,duration_minutes:input.durationMinutes,note:input.note?.trim()||null});if(error)throw fail(error);notify()}
export async function deleteCaffeineIntake(id:string){const{error}=await dataApi.from('caffeine_intakes').delete().eq('id',id);if(error)throw fail(error);notify()}
export async function listCaffeinePresets(){const{data,error}=await dataApi.from('caffeine_presets').select('id,name,caffeine_mg,kind,duration_minutes,color').order('created_at');if(error)throw fail(error);return(data??[]).map(row=>({id:String(row.id),name:String(row.name),caffeineMg:Number(row.caffeine_mg),kind:row.kind as CaffeinePreset['kind'],durationMinutes:Number(row.duration_minutes),color:String(row.color)}))}
export async function saveCaffeinePreset(input:CaffeinePresetInput,id?:string){const values={name:input.name.trim(),caffeine_mg:input.caffeineMg,kind:input.kind,duration_minutes:input.durationMinutes,color:input.color};const{error}=id?await dataApi.from('caffeine_presets').update(values).eq('id',id):await dataApi.from('caffeine_presets').insert(values);if(error)throw fail(error);notify()}
export async function deleteCaffeinePreset(id:string){const{error}=await dataApi.from('caffeine_presets').delete().eq('id',id);if(error)throw fail(error);notify()}
