import{dataApi}from'../../../lib/neon/data';import type{Subject,Task,TaskInput}from'../types'
const CHANGED='studyos:tasks-changed';export function notifyTasksChanged(){window.dispatchEvent(new Event(CHANGED))}export function onTasksChanged(listener:()=>void){window.addEventListener(CHANGED,listener);return()=>window.removeEventListener(CHANGED,listener)}
function failure(error:unknown){return new Error(error&&typeof error==='object'&&'message'in error?String(error.message):'Unknown database error')}
function mapSubject(row:Record<string,unknown>):Subject{return{id:String(row.id),name:String(row.name),color:String(row.color),archivedAt:row.archived_at?String(row.archived_at):null}}
function mapTask(row:Record<string,unknown>):Task{const relation=Array.isArray(row.subjects)?row.subjects[0]:row.subjects;return{id:String(row.id),title:String(row.title),category:row.category as Task['category'],subjectId:row.subject_id?String(row.subject_id):null,subject:relation?mapSubject(relation as Record<string,unknown>):null,dueDate:row.due_date?String(row.due_date):null,completedAt:row.completed_at?String(row.completed_at):null,createdAt:String(row.created_at)}}
export async function listTasks(){const{data,error}=await dataApi.from('tasks').select('id,title,category,subject_id,due_date,completed_at,created_at,subjects(id,name,color,archived_at)').order('completed_at',{ascending:true,nullsFirst:true}).order('due_date',{ascending:true,nullsFirst:false}).order('created_at',{ascending:false});if(error)throw failure(error);return(data??[]).map(row=>mapTask(row as Record<string,unknown>))}
export async function listSubjects(includeArchived=false){let query=dataApi.from('subjects').select('id,name,color,archived_at').order('name');if(!includeArchived)query=query.is('archived_at',null);const{data,error}=await query;if(error)throw failure(error);return(data??[]).map(row=>mapSubject(row as Record<string,unknown>))}
export async function createSubject(name:string,color:string){const{error}=await dataApi.from('subjects').insert({name:name.trim(),color});if(error)throw failure(error);notifyTasksChanged()}
export async function updateSubject(id:string,name:string,color:string){const{error}=await dataApi.from('subjects').update({name:name.trim(),color}).eq('id',id);if(error)throw error;notifyTasksChanged()}
export async function archiveSubject(id:string){const{error}=await dataApi.from('subjects').update({archived_at:new Date().toISOString()}).eq('id',id);if(error)throw error;notifyTasksChanged()}
export async function createTask(input:TaskInput){const{error}=await dataApi.from('tasks').insert({title:input.title.trim(),category:input.category,subject_id:input.category==='study'?input.subjectId:null,due_date:input.dueDate});if(error)throw error;notifyTasksChanged()}
export async function updateTask(id:string,input:TaskInput){const{error}=await dataApi.from('tasks').update({title:input.title.trim(),category:input.category,subject_id:input.category==='study'?input.subjectId:null,due_date:input.dueDate}).eq('id',id);if(error)throw error;notifyTasksChanged()}
export async function setTaskCompleted(id:string,completed:boolean){const{error}=await dataApi.from('tasks').update({completed_at:completed?new Date().toISOString():null}).eq('id',id);if(error)throw error;notifyTasksChanged()}
export async function deleteTask(id:string){const{error}=await dataApi.from('tasks').delete().eq('id',id);if(error)throw error;notifyTasksChanged()}
