import{dataApi}from'../../../lib/neon/data';import type{RoutineItem,RoutineItemInput,RoutineTemplate}from'../types'
const CHANGED='studyos:routine-changed';const notify=()=>window.dispatchEvent(new Event(CHANGED));export function onRoutineChanged(listener:()=>void){window.addEventListener(CHANGED,listener);return()=>window.removeEventListener(CHANGED,listener)}
function message(error:unknown){if(error&&typeof error==='object'&&'message'in error)return String(error.message);return'Unknown database error'}
function mapItem(row:Record<string,unknown>):RoutineItem{return{id:String(row.id),position:Number(row.position),scheduledTime:row.scheduled_time?String(row.scheduled_time).slice(0,5):null,title:String(row.title),details:row.details?String(row.details):null,completedAt:row.completed_at?String(row.completed_at):null}}
export async function getTemplate(weekday:number):Promise<RoutineTemplate>{let{data,error}=await dataApi.from('routine_templates').select('id,weekday').eq('weekday',weekday).maybeSingle();if(error)throw new Error(message(error));if(!data){const result=await dataApi.from('routine_templates').insert({weekday}).select('id,weekday').single();if(result.error)throw new Error(message(result.error));data=result.data}return{id:String(data.id),weekday:Number(data.weekday)}}
export async function listTemplateItems(templateId:string){const{data,error}=await dataApi.from('routine_template_items').select('id,position,scheduled_time,title,details').eq('template_id',templateId).order('position');if(error)throw new Error(message(error));return(data??[]).map(row=>mapItem(row as Record<string,unknown>))}
export async function saveTemplateItem(templateId:string,input:RoutineItemInput,id?:string){if(id){const{error}=await dataApi.from('routine_template_items').update({title:input.title.trim(),scheduled_time:input.scheduledTime,details:input.details?.trim()||null}).eq('id',id);if(error)throw new Error(message(error))}else{const{count,error}=await dataApi.from('routine_template_items').select('id',{count:'exact',head:true}).eq('template_id',templateId);if(error)throw new Error(message(error));const result=await dataApi.from('routine_template_items').insert({template_id:templateId,position:count??0,title:input.title.trim(),scheduled_time:input.scheduledTime,details:input.details?.trim()||null});if(result.error)throw new Error(message(result.error))}notify()}
export async function deleteTemplateItem(id:string){const{error}=await dataApi.from('routine_template_items').delete().eq('id',id);if(error)throw new Error(message(error));notify()}
export async function moveTemplateItem(items:RoutineItem[],id:string,direction:-1|1){const index=items.findIndex(item=>item.id===id),swap=index+direction;if(index<0||swap<0||swap>=items.length)return;const first=items[index],second=items[swap];const[a,b]=await Promise.all([dataApi.from('routine_template_items').update({position:second.position}).eq('id',first.id),dataApi.from('routine_template_items').update({position:first.position}).eq('id',second.id)]);if(a.error||b.error)throw new Error(message(a.error??b.error));notify()}
export async function getDailyRoutine(date:string){const ensured=await dataApi.rpc('ensure_routine_instance',{target_date:date});if(ensured.error)throw new Error(message(ensured.error));const instanceId=String(ensured.data);const{data,error}=await dataApi.from('routine_instance_items').select('id,position,scheduled_time,title,details,completed_at').eq('instance_id',instanceId).order('position');if(error)throw new Error(message(error));return(data??[]).map(row=>mapItem(row as Record<string,unknown>))}
export async function setRoutineItemCompleted(id:string,completed:boolean){const{error}=await dataApi.from('routine_instance_items').update({completed_at:completed?new Date().toISOString():null}).eq('id',id);if(error)throw new Error(message(error));notify()}
