import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { Dices, Edit3, Plus, Quote as QuoteIcon, Star, Trash2, X } from 'lucide-react'
import { createQuote, createQuoteCategory, deleteQuote, deleteQuoteCategory, listQuoteCategories, listQuotes, onQuotesChanged, updateQuote, updateQuoteCategory } from './api'
import type { Quote, QuoteCategory } from './types'
import './quotes.css'

export function QuotesPage() {
  const [quotes, setQuotes] = useState<Quote[]>([])
  const [categories, setCategories] = useState<QuoteCategory[]>([])
  const [categoryFilter, setCategoryFilter] = useState('all')
  const [query, setQuery] = useState('')
  const [editing, setEditing] = useState<Quote | null | undefined>(undefined)
  const [picked, setPicked] = useState<Quote | null>(null)
  const [error, setError] = useState('')
  const load = useCallback(async () => { try { const [nextQuotes, nextCategories] = await Promise.all([listQuotes(), listQuoteCategories()]); setQuotes(nextQuotes); setCategories(nextCategories); setError('') } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not load quotes.') } }, [])
  useEffect(() => { void load(); return onQuotesChanged(() => void load()) }, [load])
  const filtered = useMemo(() => quotes.filter(quote => (categoryFilter === 'all' || (categoryFilter === 'none' ? !quote.categoryId : quote.categoryId === categoryFilter)) && (!query || `${quote.body} ${quote.author ?? ''} ${quote.source ?? ''}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()))), [categoryFilter, query, quotes])

  return <div className="page quotes-page"><header className="quotes-heading"><div><div className="eyebrow">Collect and revisit</div><h1 className="page-title">Quotes</h1></div><button className="button primary" onClick={() => setEditing(null)}><Plus /> Quote</button></header>{error && <p className="feature-error">{error}</p>}<div className="quotes-layout"><QuoteCategories categories={categories} selected={categoryFilter} onSelect={id => { setCategoryFilter(id); setPicked(null) }} /><main className="quotes-main"><div className="quotes-search"><input type="search" placeholder="Search quotes, authors, or sources" value={query} onChange={event => setQuery(event.target.value)} /><button className="button" disabled={!filtered.some(quote => quote.isActive)} onClick={() => { const pool = filtered.filter(quote => quote.isActive); setPicked(pool[Math.floor(Math.random() * pool.length)] ?? null) }}><Dices /> Pick one</button><span>{filtered.length} quotes</span></div>{picked && <section className="quote-pick" style={{ '--quote-pick-color': picked.category?.color ?? '#89909a' } as React.CSSProperties}><blockquote>“{picked.body}”</blockquote><p>{picked.author ? `— ${picked.author}` : 'Unknown author'}{picked.source ? ` · ${picked.source}` : ''}</p></section>}<div className="quote-list">{filtered.map(quote => <article className={`card quote-row${quote.isActive ? '' : ' inactive'}`} key={quote.id}><i style={{ background: quote.category?.color ?? '#89909a' }} /><div><blockquote>“{quote.body}”</blockquote><p>{quote.author ? `— ${quote.author}` : 'Unknown author'}{quote.source ? ` · ${quote.source}` : ''}</p></div>{quote.isFavorite && <Star className="quote-favorite" fill="currentColor" />}<button onClick={() => setEditing(quote)} aria-label="Edit quote"><Edit3 /></button><button className="danger" onClick={() => { if (confirm('Delete this quote?')) void deleteQuote(quote.id) }} aria-label="Delete quote"><Trash2 /></button></article>)}</div>{!filtered.length && <div className="card empty-state"><QuoteIcon /><h2>No matching quotes</h2><p>Add a quote or change the current filters.</p></div>}</main></div>{editing !== undefined && <QuoteEditor quote={editing} categories={categories} onClose={() => setEditing(undefined)} />}</div>
}

function QuoteCategories({ categories, selected, onSelect }: { categories: QuoteCategory[]; selected: string; onSelect: (id: string) => void }) {
  const [editing, setEditing] = useState<QuoteCategory | null>(null)
  const [name, setName] = useState('')
  const [color, setColor] = useState('#719ce3')
  const reset = () => { setEditing(null); setName(''); setColor('#719ce3') }
  async function submit(event: FormEvent) { event.preventDefault(); if (editing) await updateQuoteCategory(editing.id, { name, color, dashboardEnabled: editing.dashboardEnabled }); else await createQuoteCategory(name, color); reset() }
  return <aside className="card quote-categories"><h2>Categories</h2><button className={selected === 'all' ? 'active' : ''} onClick={() => onSelect('all')}>All quotes <span>{categories.length}</span></button><button className={selected === 'none' ? 'active' : ''} onClick={() => onSelect('none')}>Uncategorized</button>{categories.map(category => <div className="quote-category-row" key={category.id}><button className={selected === category.id ? 'active' : ''} onClick={() => onSelect(category.id)}><i style={{ background: category.color }} />{category.name}</button><label title="Show this category on Dashboard"><input type="checkbox" checked={category.dashboardEnabled} onChange={() => void updateQuoteCategory(category.id, { ...category, dashboardEnabled: !category.dashboardEnabled })} />Dashboard</label><button onClick={() => { setEditing(category); setName(category.name); setColor(category.color) }} aria-label={`Edit ${category.name}`}><Edit3 /></button><button className="danger" onClick={() => { if (confirm(`Delete ${category.name}? Quotes will become uncategorized.`)) void deleteQuoteCategory(category.id) }} aria-label={`Delete ${category.name}`}><Trash2 /></button></div>)}<form className="quote-category-form" onSubmit={submit}><input placeholder="Category name" value={name} onChange={event => setName(event.target.value)} required maxLength={80} /><input type="color" value={color} onChange={event => setColor(event.target.value)} /><button className="button primary">{editing ? 'Save' : 'Add'}</button>{editing && <button type="button" className="text-button" onClick={reset}>Cancel</button>}</form></aside>
}

function QuoteEditor({ quote, categories, onClose }: { quote: Quote | null; categories: QuoteCategory[]; onClose: () => void }) {
  const [body, setBody] = useState(quote?.body ?? '')
  const [author, setAuthor] = useState(quote?.author ?? '')
  const [source, setSource] = useState(quote?.source ?? '')
  const [categoryId, setCategoryId] = useState(quote?.categoryId ?? '')
  const [isActive, setIsActive] = useState(quote?.isActive ?? true)
  const [isFavorite, setIsFavorite] = useState(quote?.isFavorite ?? false)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); try { const input = { body, author: author || null, source: source || null, categoryId: categoryId || null, isActive, isFavorite }; if (quote) await updateQuote(quote.id, input); else await createQuote(input); onClose() } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not save quote.') } finally { setSaving(false) } }
  return <div className="quote-editor-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><form className="quote-editor" onSubmit={submit}><button type="button" className="quote-editor-close" onClick={onClose}><X /></button><div><div className="eyebrow">{quote ? 'Edit' : 'New'}</div><h2>{quote ? 'Edit quote' : 'Add quote'}</h2></div><label>Quote<textarea autoFocus value={body} onChange={event => setBody(event.target.value)} required maxLength={2000} /></label><label>Author<input value={author} onChange={event => setAuthor(event.target.value)} maxLength={160} /></label><label>Source<input value={source} onChange={event => setSource(event.target.value)} maxLength={240} /></label><label>Category<select value={categoryId} onChange={event => setCategoryId(event.target.value)}><option value="">Uncategorized</option>{categories.map(category => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label className="quote-check"><input type="checkbox" checked={isActive} onChange={event => setIsActive(event.target.checked)} />Eligible for Dashboard</label><label className="quote-check"><input type="checkbox" checked={isFavorite} onChange={event => setIsFavorite(event.target.checked)} />Favorite</label>{error && <p className="form-error">{error}</p>}<div className="quote-editor-actions"><button type="button" className="button" onClick={onClose}>Cancel</button><button className="button primary" disabled={saving}>{saving ? 'Saving…' : 'Save'}</button></div></form></div>
}
